---
title: "Gov-50 Final Project Idea"
author: "Syd Sanders"
description: "Homelessness Policy Analytics"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I have not decided what I want to do my final project on yet, so these thoughts are subject to change. However, I might be interested in analyzing the efficacy of Cambridge housing policy for the homeless. I am a volunteer Supervisor at the Harvard Square Homeless Shelter, and we use a data platform called the Homeless Management Information System (HMIS). There is a ton of data in here about the experiences with homelessness of all the houseless in Cambridge who access services, as well as housing placement efficacy data. I want to analyze how effective different policies are at helping alleviate homelessness, both temporarily and in the long term. I would also probably use the national government's yearly homelessness reports, which are informed in Massachusetts by the HMIS system. 

## Project Proposal

My project topic is evaluating the efficacy of different homelessness housing policies in the city of Cambridge. My research question is: which policy approach to homelessness leads to the highest levels of entry into permanent housing for the homeless in Cambridge, Massachusetts? My data set will come from the Homeless Management Information System data for Cambridge. HMIS is a US Dept of Housing and Urban Development program tracking data about the homeless in localities across the US. [Here](https://www.hudexchange.info/programs/hmis/) is the website. To obtain this data, I am emailing Marianne Colangelo, the HMIS Project Manager for the City of Cambridge. I will most likely have access to this data because I am a trained Supervisor at the Harvard Square Homeless Shelter and have an account on HMIS. I will do a comparison study of two different housing policy solutions to homelessness, probably the City of Cambridge's Emergency Housing Voucher Program ("EHV", via Section 8) and HomeStart, a more community-based housing plan. These will be my independent/explanatory variables - participation in a homelessness policy - and the dependent variable will be rates of acquisition of long-term housing for the homeless. I will have a control also of the homeless who accessed no such programs and their rates of obtaining long term housing. My hypothesis is that if homeless residents of Cambridge access HomeStart, they will have greater rates of being in long-term housing after the program than homeless residents who use Section 8 EHV plans. I hypothesize this because there is some evidence that community-based solutions work better than non-community solutions like Section 8. I will measure my outcome variable of obtaining long-term housing because that is a variable within the HMIS data I plan to obtain. It is measured as people who make it into housing units through policies aimed at alleviating homelessness and remain there for longer than 3 months. My hypothesis will be supported if there is evidence that those who participate in HomeStart have higher rates of making it into long-term housing than those who use EHV. My hypothesis will be disproved if there is no such relationship. 

